# This is a basic workflow to help you get started with Actions

name: download

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget https://ia801200.us.archive.org/zip_dir.php?path=/31/items/Element-XPize-XP-2k3-Eng.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: Element-XPize-XP-2k3-Eng.zip
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: Element-XPize-XP-2k3-Eng
          draft: false
          prerelease: false
          files: |
            Element-XPize-XP-2k3-Eng.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
